### ISSUE TITLE
sendAudio的时候一直返回0

### ISSUE THREAD

**Issue by wenfer** [telegant/mod_asr#6]
但是datalen为320，toHexString打印的全部是F，不知道是不是溢出了，可以指点一下吗

**Comment by wenfer** [comment]
还有那个aleg是什么意思，我看你命令传了bleg，但是代码里判断的是aleg

**Comment by wenfer** [comment]
sdk2.0的sendAudio入参是const char* data，但是3.0的入参是const uint8_t * data   请问如何转换呢

**Comment by telegant** [comment]
换最新的SDK，2.0的已经废弃了

**Comment by wenfer** [comment]
@telegant 我用的是3.0的sdk

**Comment by telegant** [comment]
@wenfer  3.x的API和数据结构都变了，不建议使用这个demo
